### ISSUE TITLE
Letter shortcut to jump to some actions

### ISSUE THREAD

**Issue by outscale-mgo** [outscale/osc-tui#90]
It would be very useful to have letter shortcut to jump to some actions:
for examples `C` could be use to Create (Instance/Volume...)
`I`,`N`,`V`,`M`, `S` could be use to jump to Instance, Nets, Volumes, Image, Security grid.

It would be nice to have the letter use for the shortcut in Color in the menu too.

Note that the colour could be complex to implement, so this might be made in another PR, with a new issue.

**Comment by jerome-jutteau** [comment]
+1 for action shortcuts but not for navigation between resources

What I would do:
- `c`: create new resource type depending of current view
- `r`: refresh view
- `u`: update selected resource if possible
- `d`: delete selected resource (with confirmation)
- `q`: Back to profile selection application. If already on profile selection: quit.
- `?`: Show help about shortcuts
